name: CoreSystem
version: '${version}'
main: org.dasultra.main.Main
api-version: '1.20'
authors: [DasUltra]
description: CoreSystem for TeamUltra
website: team-ultra.eu

commands:
  gamemode:
    aliases:
      - gm
    description: Gamemode
  feed:
      description: Feed