name: CoreSystem
version: '${version}'
main: org.dasultra.main.Main
api-version: '1.20'
authors: [DasUltra]
description: CoreSystem for TeamUltra
website: team-ultra.eu

commands:
  gamemode:
    aliases:
      - gm
  feed:
  heal:
  fly:
  invsee:
    aliases:
      - inv
      - inventory
  enderchest:
    aliases:
      - ec
      - echest
  time:
  spawn:
  setspawn:
  warp:
  setwarp:
  delwarp:
  head:
    aliases:
      - skull
  clear:
  craft:
    aliases:
      - workbench
      - wb
  rename:
  teleport:
    aliases:
      - tp
  teleporthere:
    aliases:
      - tphere
  sign:
  clearchat:
    aliases:
      - cc
  trash:
  glow:
  ping: